initialization
setUpNotas

	nota1 := Nota conTitulo: 'nota1' texto:'esta es la nota1 para el test' tags: (Set newFrom:#('tag1' 'tag2' 'tag3')).
	nota2 := Nota conTitulo: 'nota2' texto:'esta es la nota2 para el test' tags: (Set withAll:#('tag4' 'tag5' 'tag6')).
	nota3 := Nota conTitulo: 'nota3' texto:'esta es la nota3 para el test' tags: (Set withAll:#('tag7' 'tag8' 'tag9')).
	nota4 := Nota conTitulo: 'nota4' texto:'esta es la nota4 para el test' tags: (Set withAll:#('tag10' 'tag11' 'tag12')).